export const GET_USER_DATA="GET_USER_DATA";
export const UPDATE_SELECTED_USERID ="UPDATE_SELECTED_USERID";
export const UPDATE_SELECTED_USER ="UPDATE_SELECTED_USER";
export const POPULATE_SELECTED_USER_IN_FORM ="POPULATE_SELECTED_USER_IN_FORM";
export const GET_FILTERED_USER_DATA = "GET_FILTERED_USER_DATA";